### ISSUE TITLE
Error loading dependencies on dash-daq

### ISSUE THREAD

**Issue by privatejava** [while0x1/stealthWallet#1]
I followed exactly as per README and installed the packages and run app.py but facing this issue when I tried to view in browser http://localhost:8050 . I tried to check my da

```
Port connected
content.js:19 initializing content script
inject.js:19 injecting content script
dash_renderer.v2_16_0m1709707517.min.js:2 Error: dash_daq was not found.
    at Object.resolve (dash_renderer.v2_16_0m1709707517.min.js:2:71383)
    at y (dash_renderer.v2_16_0m1709707517.min.js:2:242247)
    at dash_renderer.v2_16_0m1709707517.min.js:2:242982
    at Array.forEach (<anonymous>)
    at g (dash_renderer.v2_16_0m1709707517.min.js:2:242898)
    at Array.forEach (<anonymous>)
    at m (dash_renderer.v2_16_0m1709707517.min.js:2:243164)
    at dash_renderer.v2_16_0m1709707517.min.js:2:243382
    at dash_renderer.v2_16_0m1709707517.min.js:2:243442
    at dash_renderer.v2_16_0m1709707517.min.js:2:45047
```
I tried to check for daq version too by using this code 
`print(daq.__version__)` and it outputs `0.5.0`

Python:  3.10.12
pip: 22.0.2 
OS: ubuntu 22.04 LTS

**Comment by while0x1** [comment]
Thanks for reaching out with an issue! - two questions I can see it cannot find the dash_daq library from the error message have you pip installed dash_daq as per the readme? In the Console do you see any error messages after you run python app.py? What browser are you using?

**Comment by while0x1** [comment]
The dash_daq library is only used for the send_all button on the wallet.py file, but the state of that switch is used in a callback for the tx_submit_click function, I will look for another library for a switch that might be compatible with your OS if you can confirm you have pip installed dash_daq and this is a ubuntu/browser issue

**Comment by privatejava** [comment]
Yeah daq is installed but i am not sure why it could not load it in web. I can confirm that it was correctly installed 
`print(daq.__version__)` and it outputs `0.5.0`

**Comment by while0x1** [comment]
can you let me know what browser you are using - then I can try and write some python code that will load the correct component library dependent on browser so i dont need to write two seperate versions of the wallet.py file.. so I run stealthwallet on ubuntu 22.04 on a server on my network - but I access it through a windows machine using brave browser which loads all the dependencies without issue.

**Comment by while0x1** [comment]
I have pushed a new wallet.py file and deprecated the old one - the new wallet.py file uses the dcc slider library - the component is less aesthetic but it should fix this dependency issue. Let me know how it goes.  People are free to use deprecated version by commenting out either file they prefer..

**Comment by privatejava** [comment]
Wow this now works :) Thank you !!
